### ISSUE TITLE
Entirely disabling the redirect

### ISSUE THREAD

**Issue by WyriHaximus** [middlewares/https#2]
Tried using this middleware in a project today and upon deployment it put the entire site in a redirect loop back to itself. What would you think of a flag to entirely disabling the redirect? (I gladly craft a PR for it.)

In my set up that is handled in `nginx` config way before it hits PHP. And I'm not setting the headers it's checking for.

**Comment by oscarotero** [comment]
If I understood correctly, in your set up nginx removes the https scheme and no http headers are sent to detect this manipulation?

**Comment by WyriHaximus** [comment]
My `nginx` set up redirects all requests on `HTTP` to `HTTPS`. On `HTTPS` the request is proxied to a `ReactPHP` application which runs internally on `HTTP`.

**Comment by oscarotero** [comment]
Ok. If reactPHP does not add the `X-Forwarded-*` header, I guess we can add this option.

**Comment by WyriHaximus** [comment]
Ok cool I'll prepare a PR.
